# Generated by Django 3.2.13 on 2022-08-31 00:56

import apps.home.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio_file', models.FileField(blank=True, null=True, storage=apps.home.models.OverwriteStorage(), upload_to='bio')),
                ('picture_file', models.FileField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture_file', models.FileField(blank=True, null=True, upload_to='project_pics')),
                ('budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('members', models.ManyToManyField(to='home.UserProfile')),
            ],
        ),
    ]
